#!/bin/bash

###############################
#Check if program is installed#
###############################
dpkg -l microsoft-edge-dev |grep -q ^ii

if [ $? -eq 0 ]; then
         if [ -e "/usr/bin/microsoft-edge" ]; then
                  zenity --info --title="Information" --text="Google Chrome is already installed" --no-wrap &
                  exit 0
         fi
fi

################
#Check for root#
################
if [ ! $(whoami) = "root" ]; then
    zenity --question --title="You found a secret!" --text "It's a secret to everybody." --no-wrap --ok-label="Install Microsoft Edge Development Builds"

    if [ ! $? -eq 0 ]; then
        exit
    fi

    pkexec "$0"
    
    if [ $? -eq 127 ]; then
        exit 0
    fi    
    
    ######################
    #Double Check Package#
    ######################
    if [ -e "/usr/bin/microsoft-edge" ]; then
            zenity --info --title="Installation Complete" --text="Microsoft Edge was successfully installed" --no-wrap &
            exit 0
    fi
    #######
    #Error#
    #######
    zenity  --error --text="Feren OS couldn't install Microsoft Edge successfully

A log can be found at File System/tmp/msedge-install-log" --title="Error" --no-wrap &
    exit 0
fi

###################################
#Check if program is not installed#
###################################
dpkg -l microsoft-edge-dev |grep -q ^ii

if [ ! $? -eq 0 ]; then
         if [ ! -e "/usr/bin/microsoft-edge" ]; then

#################
#Install program#
#################
        #Log output
        exec 1>/tmp/msedge-install-log 2>&1
        
                if [ ! -f /etc/apt/sources.list.d/microsoft-edge-dev.list ]; then
                    apt-key add - >/dev/null 2>&1 <<KEYDATA
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1.4.7 (GNU/Linux)

mQENBFYxWIwBCADAKoZhZlJxGNGWzqV+1OG1xiQeoowKhssGAKvd+buXCGISZJwT
LXZqIcIiLP7pqdcZWtE9bSc7yBY2MalDp9Liu0KekywQ6VVX1T72NPf5Ev6x6DLV
7aVWsCzUAF+eb7DC9fPuFLEdxmOEYoPjzrQ7cCnSV4JQxAqhU4T6OjbvRazGl3ag
OeizPXmRljMtUUttHQZnRhtlzkmwIrUivbfFPD+fEoHJ1+uIdfOzZX8/oKHKLe2j
H632kvsNzJFlROVvGLYAk2WRcLu+RjjggixhwiB+Mu/A8Tf4V6b+YppS44q8EvVr
M+QvY7LNSOffSO6Slsy9oisGTdfE39nC7pVRABEBAAG0N01pY3Jvc29mdCAoUmVs
ZWFzZSBzaWduaW5nKSA8Z3Bnc2VjdXJpdHlAbWljcm9zb2Z0LmNvbT6JATUEEwEC
AB8FAlYxWIwCGwMGCwkIBwMCBBUCCAMDFgIBAh4BAheAAAoJEOs+lK2+EinPGpsH
/32vKy29Hg51H9dfFJMx0/a/F+5vKeCeVqimvyTM04C+XENNuSbYZ3eRPHGHFLqe
MNGxsfb7C7ZxEeW7J/vSzRgHxm7ZvESisUYRFq2sgkJ+HFERNrqfci45bdhmrUsy
7SWw9ybxdFOkuQoyKD3tBmiGfONQMlBaOMWdAsic965rvJsd5zYaZZFI1UwTkFXV
KJt3bp3Ngn1vEYXwijGTa+FXz6GLHueJwF0I7ug34DgUkAFvAs8Hacr2DRYxL5RJ
XdNgj4Jd2/g6T9InmWT0hASljur+dJnzNiNCkbn9KbX7J/qK1IbR8y560yRmFsU+
NdCFTW7wY0Fb1fWJ+/KTsC4=
=J6gs
-----END PGP PUBLIC KEY BLOCK-----
KEYDATA
                    if [ ! $? -eq 0 ]; then
                        exit 1
                    fi
                    echo -e "deb [arch=amd64] http://packages.microsoft.com/repos/edge/ stable main" > /etc/apt/sources.list.d/microsoft-edge-dev.list
                fi
                apt-get update
                apt-get -y install microsoft-edge-dev
         fi
         exit
fi

#######
#Error#
#######
zenity  --error --text="An error occured while initiating the Microsoft Edge installation process" --title="Error" --no-wrap &
exit 0
