#!/bin/bash

###################################
#Check if program is not installed#
###################################
dpkg -l microsoft-edge-dev |grep -q ^ii

if [ ! $? -eq 0 ]; then
         if [ ! -e "/usr/bin/microsoft-edge" ]; then
                  zenity --info --title="Information" --text="Microsoft Edge is not installed" --no-wrap &
                  exit 0
         fi
fi

################
#Check for root#
################
if [ ! "$(whoami)" = "root" ]; then
    zenity --question --title="Continue?" --text "Are you sure you want to remove Microsoft Edge?" --no-wrap

    if [ ! $? -eq 0 ]; then
            exit
    fi
    
    pkexec "$0" $@
    
    if [ $? -eq 127 ]; then
        exit 0
    fi
    
    ######################
    #Double Check Package#
    ######################
    dpkg --get-selections | grep -P -q "microsoft-edge-dev\t*install"

    if [ ! $? -eq 0 ]; then
            if [ ! -e "/usr/bin/microsoft-edge" ]; then
                    zenity --info --title="Uninstalled Microsoft Edge" --text="Microsoft Edge was successfully removed" --no-wrap &
                    exit 0
            fi
            #######
            #Error#
            #######
            zenity  --error --text="Feren OS couldn't remove Microsoft Edge successfully

A log can be found at File System/tmp/msedge-removal-log" --title="Error" --no-wrap &
            exit 0
    fi
fi

###############################
#Check if program is installed#
###############################
dpkg -l microsoft-edge-dev |grep -q ^ii

if [ $? -eq 0 ]; then
         if [ -e "/usr/bin/microsoft-edge" ]; then

###################
#Uninstall program#
###################
        #Log output
        exec 1>/tmp/msedge-removal-log 2>&1
        
                  apt-get -y remove microsoft-edge-dev
         fi
         exit
fi

#######
#Error#
#######
zenity  --error --text="An error occured while initiating the Microsoft Edge removal process" --title="Error" --no-wrap &
exit 0
