#!/bin/bash

###############################
#Check if program is installed#
###############################
dpkg -l firefox |grep -q ^ii

if [ $? -eq 0 ]; then
         if [ -e "/usr/bin/firefox" ]; then
                  zenity --info --title="Information" --text="Mozilla Firefox is already installed" --no-wrap &
                  exit 0
         fi
fi



################
#Check for root#
################
if [ ! $(whoami) = "root" ]; then
    zenity --question --title="Continue?" --text "The use of Mozilla Firefox is governed by the Terms found at
https://www.mozilla.org/en-US/about/legal/terms/firefox/,
are you sure you want to install Mozilla Firefox?" --no-wrap

    if [ ! $? -eq 0 ]; then
           exit
    fi

    pkexec "$0"
    
    if [ $? -eq 127 ]; then
        exit 0
    fi
    
    ######################
    #Double Check Package#
    ######################
    if [ -e "/usr/bin/firefox" ]; then
            zenity --info --title="Installation Complete" --text="Mozilla Firefox was successfully installed" --no-wrap &
            exit 0
    fi
    #######
    #Error#
    #######
    zenity  --error --text="Feren OS couldn't install Mozilla Firefox successfully

A log can be found at File System/tmp/firefox-install-log" --title="Error" --no-wrap &
    exit 0
fi

###################################
#Check if program is not installed#
###################################
dpkg -l firefox |grep -q ^ii

if [ ! $? -eq 0 ]; then
         if [ ! -e "/usr/bin/firefox" ]; then

#################
#Install program#
#################
        #Log output
        exec 1>/tmp/firefox-install-log 2>&1
        
                  apt-get update
                  apt-get -y install firefox
         fi
         exit
fi

#######
#Error#
#######
zenity  --error --text="An error occured while initiating the Mozilla Firefox installation process." --title="Error" --no-wrap &
exit 0
