#!/bin/bash

###################################
#Check if program is not installed#
###################################
flatpak list | grep org.mozilla.firefox

if [ ! $? -eq 0 ] && [ ! -f /usr/bin/firefox ]; then
    zenity --info --title="Information" --text="Mozilla Firefox is not installed" --no-wrap &
    exit 0
fi

################
#Check for root#
################
if [ ! "$(whoami)" = "root" ]; then
    zenity --question --title="Continue?" --text "Are you sure you want to remove Mozilla Firefox?" --no-wrap

    if [ ! $? -eq 0 ]; then
            exit
    fi
    
    pkexec "$0" $@
    
    if [ $? -eq 127 ]; then
        exit 0
    fi
    
    ######################
    #Double Check Package#
    ######################
    flatpak list | grep org.mozilla.firefox

    if [ ! $? -eq 0 ] && [ ! -f /usr/bin/firefox ]; then
        zenity --info --title="Uninstalled Mozilla Firefox" --text="Mozilla Firefox was successfully removed" --no-wrap &
        exit 0
            #######
            #Error#
            #######
    fi
    zenity  --error --text="Feren OS couldn't remove Mozilla Firefox successfully

A log can be found at File System/tmp/firefox-removal-log" --title="Error" --no-wrap &
    exit 0
fi

###############################
#Check if program is installed#
###############################
flatpak list | grep org.mozilla.firefox

if [ $? -eq 0 ] || [ -f /usr/bin/firefox ]; then

###################
#Uninstall program#
###################
        #Log output
        exec 1>/tmp/firefox-removal-log 2>&1
        
        flatpak remove org.mozilla.firefox -y
        if [ -f "/usr/bin/firefox" ]; then apt purge firefox -y; fi #Legacy support
        exit
fi

#######
#Error#
#######
zenity  --error --text="An error occured while initiating the Mozilla Firefox removal process" --title="Error" --no-wrap &
exit 0
