#!/bin/bash

###################################
#Check if program is not installed#
###################################
dpkg -l firefox |grep -q ^ii

if [ ! $? -eq 0 ]; then
         if [ ! -e "/usr/bin/firefox" ]; then
                  zenity --info --title="Information" --text="Mozilla Firefox is not installed" --no-wrap &
                  exit 0
         fi
fi

################
#Check for root#
################
if [ ! "$(whoami)" = "root" ]; then
    zenity --question --title="Continue?" --text "Are you sure you want to remove Mozilla Firefox?" --no-wrap

    if [ ! $? -eq 0 ]; then
            exit
    fi
    
    pkexec "$0" $@
    
    if [ $? -eq 127 ]; then
        exit 0
    fi
    
    ######################
    #Double Check Package#
    ######################
    dpkg -l firefox |grep -q ^ii

    if [ ! $? -eq 0 ]; then
            if [ ! -e "/usr/bin/firefox" ]; then
                    zenity --info --title="Uninstalled Mozilla Firefox" --text="Mozilla Firefox was successfully removed" --no-wrap &
                    exit 0
            fi
            #######
            #Error#
            #######
            zenity  --error --text="Feren OS couldn't remove Mozilla Firefox successfully

A log can be found at File System/tmp/firefox-removal-log" --title="Error" --no-wrap &
            exit 0
    fi
fi

###############################
#Check if program is installed#
###############################
dpkg -l firefox |grep -q ^ii

if [ $? -eq 0 ]; then
         if [ -e "/usr/bin/firefox" ]; then

###################
#Uninstall program#
###################
        #Log output
        exec 1>/tmp/firefox-removal-log 2>&1
        
                  apt-get -y remove firefox
         fi
         exit
fi

#######
#Error#
#######
zenity  --error --text="An error occured while initiating the Mozilla Firefox removal process" --title="Error" --no-wrap &
exit 0
