#!/bin/bash

###############################
#Check if program is installed#
###############################
dpkg -l chromium-browser |grep -q ^ii

if [ $? -eq 0 ]; then
         if [ -e "/usr/bin/chromium-browser" ]; then
                  zenity --info --title="Information" --text="Chromium is already installed" --no-wrap &
                  exit 0
         fi
fi

################
#Check for root#
################
if [ ! $(whoami) = "root" ]; then
    zenity --question --title="Continue?" --text "Are you sure you want to install Chromium?" --no-wrap

    if [ ! $? -eq 0 ]; then
            exit
    fi

    pkexec "$0"
    
    if [ $? -eq 127 ]; then
        exit 0
    fi
    
    ######################
    #Double Check Package#
    ######################
    if [ -e "/usr/bin/chromium-browser" ]; then
            zenity --info --title="Installation Complete" --text="Chromium was successfully installed" --no-wrap &
            exit 0
    fi
    #######
    #Error#
    #######
    zenity  --error --text="Feren OS couldn't install Chromium successfully

A log can be found at File System/tmp/chromium-install-log" --title="Error" --no-wrap &
    exit 0
fi

###################################
#Check if program is not installed#
###################################
dpkg -l chromium-browser |grep -q ^ii

if [ ! $? -eq 0 ]; then
         if [ ! -e "/usr/bin/chromium-browser" ]; then

#################
#Install program#
#################
        #Log output
        exec 1>/tmp/chromium-install-log 2>&1
        
                  apt-get update
                  apt-get -y install chromium-browser
         fi
         exit
fi

#######
#Error#
#######
zenity  --error --text="An error occured while initiating the Chromium installation process" --title="Error" --no-wrap &
exit 0
