#!/bin/bash

###############################
#Check if program is installed#
###############################
dpkg -l chromium |grep -q ^ii

if [ $? -eq 0 ]; then
         if [ -e "/usr/bin/chromium" ]; then
                  zenity --info --title="Information" --text="Chromium is already installed" --no-wrap &
                  exit 0
         fi
fi

################
#Check for root#
################
if [ ! $(whoami) = "root" ]; then
    zenity --question --title="Continue?" --text "Are you sure you want to install Chromium?" --no-wrap

    if [ ! $? -eq 0 ]; then
            exit
    fi

    pkexec "$0"
    
    if [ $? -eq 127 ]; then
        exit 0
    fi
    
    ######################
    #Double Check Package#
    ######################
    if [ -e "/usr/bin/chromium" ]; then
            zenity --info --title="Installation Complete" --text="Chromium was successfully installed" --no-wrap &
            exit 0
    fi
    #######
    #Error#
    #######
    zenity  --error --text="Feren OS couldn't install Chromium successfully

A log can be found at File System/tmp/chromium-install-log" --title="Error" --no-wrap &
    exit 0
fi

###################################
#Check if program is not installed#
###################################
dpkg -l chromium |grep -q ^ii

if [ ! $? -eq 0 ]; then
         if [ ! -e "/usr/bin/chromium" ]; then

#################
#Install program#
#################
        #Log output
        exec 1>/tmp/chromium-install-log 2>&1
        
        #Add Linux Mint's repository and restrict it to just chromium
        wget http://packages.linuxmint.com/pool/main/l/linuxmint-keyring/linuxmint-keyring_2016.05.26_all.deb -O /tmp/linuxmint-keyring.deb
        dpkg -i /tmp/linuxmint-keyring.deb
        rm -f /tmp/linuxmint-keyring.deb
        apt-get -f install -y
        echo "deb http://packages.linuxmint.com ulyana main upstream #id:linuxmint_main" > /etc/apt/sources.list.d/linux-mint.list
        echo '# Do not install anything other than allowed packages from the Linux Mint repos
Package: *
Pin: origin "packages.linuxmint.com"
Pin-Priority: -10

# Pattern includes "chromium"
Package: chromium*
Pin: origin "packages.linuxmint.com"
Pin-Priority: 700

# Is package "linuxmint-keyring"
Package: linuxmint-keyring
Pin: origin "packages.linuxmint.com"
Pin-Priority: 700' > /etc/apt/preferences.d/lm-only-chromium.pref
        
                  apt-get update
                  apt-get -y install chromium
         fi
         exit
fi

#######
#Error#
#######
zenity  --error --text="An error occured while initiating the Chromium installation process" --title="Error" --no-wrap &
exit 0
