#!/bin/bash



################
#Check for root#
################
if [ ! $USERNAME = "root" ]; then
    gksudo --description="Web Browser Manager" /usr/share/browser-manager/web/install
    exit 0
fi

##########
#Question#
##########
zenity --question --title="Continue?" --text "Are you sure you want to continue?"

if [ ! $? -eq 0 ]; then
           exit
fi

###############################
#Check if program is installed#
###############################
dpkg --get-selections | grep -P -q "epiphany-browser\t*install"

if [ $? -eq 0 ]; then
         if [ -e "/usr/bin/epiphany-browser" ]; then
                  zenity --info --title="Information" --text="Web is already installed!"
                  exit 0
         fi
fi

###################################
#Check if program is not installed#
###################################
dpkg --get-selections | grep -P -q "epiphany-browser\t*install"

if [ ! $? -eq 0 ]; then
         if [ ! -e "/usr/bin/epiphany-browser" ]; then

#################
#Install program#
#################
                  apt-get update | zenity --progress --title="Installing..." --text="Updating package archive..." --pulsate --auto-close && apt-get -y install epiphany-browser epiphany-browser-data | zenity --progress --title="Installing..." --text="Downloading and Installing..." --pulsate --auto-close
         fi
         ######################
         #Double Check Package#
         ######################
         dpkg --get-selections | grep -P -q "epiphany-browser\t*install"

         if [ $? -eq 0 ]; then
                  if [ -e "/usr/bin/epiphany-browser" ]; then
                           zenity --info --title="Installation Complete" --text="Web installed successfully!"
                           exit 0
                  fi
                  #######
                  #Error#
                  #######
                  zenity  --error --text="An error occured." --title="Error"
                  exit 0
         fi
fi

#######
#Error#
#######
zenity  --error --text="An error occured." --title="Error"
exit 0
