#!/bin/bash



################
#Check for root#
################
if [ ! $USERNAME = "root" ]; then
    gksudo --description="Web Browser Manager" /usr/share/browser-manager/web/uninstall
    exit 0
fi

##########
#Question#
##########
zenity --question --title="Continue?" --text "Are you sure you want to continue?"

if [ ! $? -eq 0 ]; then
           exit
fi

###################################
#Check if program is not installed#
###################################
dpkg --get-selections | grep -P -q "epiphany-browser\t*install"

if [ $? -ne 0 ]; then
         if [ ! -e "/usr/bin/epiphany-browser" ]; then
                  zenity --info --title="Information" --text="Web is not installed!"
                  exit 0
         fi
fi

###################
#Uninstall program#
###################
                  apt-get -y remove epiphany-browser epiphany-browser-data | zenity --progress --title="Uninstalling..." --text="Uninstalling..." --pulsate --auto-close
         ######################
         #Double Check Package#
         ######################
         dpkg --get-selections | grep -P -q "epiphany-browser\t*install"

         if [ $? -ne 0 ]; then
                  if [ ! -e "/usr/bin/epiphany-browser" ]; then
                           zenity --info --title="Uninstalled Web" --text="Web uninstalled successfully!"
                           exit 0
                  fi
                  #######
                  #Error#
                  #######
                  zenity  --error --text="An error occured." --title="Error"
                  exit 0
         fi

#######
#Error#
#######
zenity  --error --text="An error occured." --title="Error"
exit 0
