#!/bin/bash

###################################
#Check if program is not installed#
###################################
dpkg --get-selections | grep -P -q "epiphany-browser\t*install"

if [ ! $? -eq 0 ]; then
         if [ ! -e "/usr/bin/epiphany-browser" ]; then
                  zenity --info --title="Information" --text="GNOME Web is not installed" --no-wrap &
                  exit 0
         fi
fi

################
#Check for root#
################
if [ ! "$(whoami)" = "root" ]; then
    zenity --question --title="Continue?" --text "Are you sure you want to remove GNOME Web?" --no-wrap

    if [ ! $? -eq 0 ]; then
            exit
    fi
    
    pkexec "$0" $@
    
    if [ $? -eq 127 ]; then
        exit 0
    fi
    
    ######################
    #Double Check Package#
    ######################
    dpkg --get-selections | grep -P -q "epiphany-browser\t*install"

    if [ ! $? -eq 0 ]; then
            if [ ! -e "/usr/bin/epiphany-browser" ]; then
                    zenity --info --title="Uninstalled GNOME Web" --text="GNOME Web was successfully removed" --no-wrap &
                    exit 0
            fi
            #######
            #Error#
            #######
            zenity  --error --text="Feren OS couldn't remove GNOME Web successfully

A log can be found at File System/tmp/epiphany-removal-log" --title="Error" --no-wrap &
            exit 0
    fi
fi

###############################
#Check if program is installed#
###############################
dpkg --get-selections | grep -P -q "epiphany-browser\t*install"

if [ $? -eq 0 ]; then
         if [ -e "/usr/bin/epiphany-browser" ]; then

###################
#Uninstall program#
###################
        #Log output
        exec 1>/tmp/epiphany-removal-log 2>&1
        
                  apt-get -y remove epiphany-browser
         fi
         exit
fi

#######
#Error#
#######
zenity  --error --text="An error occured while initiating the GNOME Web removal process." --title="Error" --no-wrap &
exit 0
