#!/bin/bash

###############################
#Check if program is installed#
###############################
dpkg -l vivaldi-stable |grep -q ^ii

if [ $? -eq 0 ]; then
         if [ -e "/usr/bin/vivaldi" ]; then
                  zenity --info --title="Information" --text="Vivaldi is already installed" --no-wrap &
                  exit 0
         fi
fi



################
#Check for root#
################
if [ ! $(whoami) = "root" ]; then
    zenity --question --title="Continue?" --text "The usage of Vivaldi is governed by the Vivaldi EULA and Privacy Policy
found on https://vivaldi.com/privacy/, are you sure you want to install
Vivaldi?" --no-wrap

    if [ ! $? -eq 0 ]; then
           exit
    fi

    pkexec "$0"
    
    if [ $? -eq 127 ]; then
        exit 0
    fi
    
    ######################
    #Double Check Package#
    ######################
    if [ -e "/usr/bin/vivaldi" ]; then
            zenity --info --title="Installation Complete" --text="Vivaldi was successfully installed" --no-wrap &
            exit 0
    fi
    #######
    #Error#
    #######
    zenity  --error --text="Feren OS couldn't install Vivaldi successfully

A log can be found at File System/tmp/vivaldi-install-log" --title="Error" --no-wrap &
    exit 0
fi


###################################
#Check if program is not installed#
###################################
dpkg -l vivaldi-stable |grep -q ^ii

if [ ! $? -eq 0 ]; then
         if [ ! -e "/usr/bin/vivaldi" ]; then

#################
#Install program#
#################
        #Log output
        exec 1>/tmp/vivaldi-install-log 2>&1
        
                if [ ! -f /etc/apt/sources.list.d/vivaldi.list ]; then
                    wget -q -O - http://repo.vivaldi.com/stable/linux_signing_key.pub | apt-key add -
                    if [ ! $? -eq 0 ]; then
                        exit 1
                    fi
                    echo -e "deb http://repo.vivaldi.com/stable/deb/ stable main" > /etc/apt/sources.list.d/vivaldi.list
                fi
                apt-get update
                apt-get -y install vivaldi-stable feren-vivaldi-theme
         fi
         exit
fi

#######
#Error#
#######
zenity  --error --text="An error occured while initiating the Vivaldi installation process" --title="Error" --no-wrap &
exit 0
