#!/bin/bash

###################################
#Check if program is not installed#
###################################
dpkg --get-selections | grep -P -q "opera-stable\t*install"

if [ ! $? -eq 0 ]; then
         if [ ! -e "/usr/bin/opera" ]; then
                  zenity --info --title="Information" --text="Opera is not installed" --no-wrap &
                  exit 0
         fi
fi

################
#Check for root#
################
if [ ! "$(whoami)" = "root" ]; then
    zenity --question --title="Continue?" --text "Are you sure you want to remove Opera?" --no-wrap

    if [ ! $? -eq 0 ]; then
            exit
    fi
    
    pkexec "$0" $@
    
    if [ $? -eq 127 ]; then
        exit 0
    fi
    
    ######################
    #Double Check Package#
    ######################
    dpkg --get-selections | grep -P -q "opera-stable\t*install"

    if [ ! $? -eq 0 ]; then
            if [ ! -e "/usr/bin/opera" ]; then
                    zenity --info --title="Uninstalled Opera" --text="Opera was successfully removed" --no-wrap &
                    exit 0
            fi
            #######
            #Error#
            #######
            zenity  --error --text="Feren OS couldn't remove Opera successfully

A log can be found at File System/tmp/opera-removal-log" --title="Error" --no-wrap &
            exit 0
    fi
fi

###############################
#Check if program is installed#
###############################
dpkg --get-selections | grep -P -q "opera-stable\t*install"

if [ $? -eq 0 ]; then
         if [ -e "/usr/bin/opera" ]; then

###################
#Uninstall program#
###################
        #Log output
        exec 1>/tmp/opera-removal-log 2>&1
        
                  apt-get -y remove opera-stable
         fi
         exit
fi

#######
#Error#
#######
zenity  --error --text="An error occured while initiating the Opera removal process" --title="Error" --no-wrap &
exit 0
