#!/bin/bash



################
#Check for root#
################
if [ ! $USERNAME = "root" ]; then
    gksudo --description="Web Browser Manager" /usr/share/browser-manager/midori/uninstall
    exit 0
fi

##########
#Question#
##########
zenity --question --title="Continue?" --text "Are you sure you want to continue?"

if [ ! $? -eq 0 ]; then
           exit
fi

###################################
#Check if program is not installed#
###################################
dpkg --get-selections | grep -q "midori.*	install"

if [ ! $? -eq 0 ]; then
         if [ ! -e "/usr/bin/midori" ]; then
                  zenity --info --title="Information" --text="Midori is not installed!"
                  exit 0
         fi
fi

###############################
#Check if program is installed#
###############################
dpkg --get-selections | grep -q "midori.*	install"

if [ $? -eq 0 ]; then
         if [ -e "/usr/bin/midori" ]; then

###################
#Uninstall program#
###################
                  apt-get -y remove midori | zenity --progress --title="Uninstalling..." --text="Uninstalling..." --pulsate --auto-close
         fi
         ######################
         #Double Check Package#
         ######################
         dpkg --get-selections | grep -q "midori.*	install"

         if [ ! $? -eq 0 ]; then
                  if [ ! -e "/usr/bin/midori" ]; then
                           zenity --info --title="Uninstalled Midori" --text="Midori uninstalled successfully!"
                           exit 0
                  fi
                  #######
                  #Error#
                  #######
                  zenity  --error --text="An error occured." --title="Error"
                  exit 0
         fi
fi

#######
#Error#
#######
zenity  --error --text="An error occured." --title="Error"
exit 0
